package com.example.firebasertdb.utils

object Constants {
    const val databaseURL = "https://fir-rtdb-cc377-default-rtdb.europe-west1.firebasedatabase.app/"
    const val DRIVER_INFO_REFERENCE = "DriverInfo"
    const val type = "PetOwnerOrPetSitter"
    var type_select:String = "PetOwnerOrPetSitter"
    const val RC_SIGN_IN=1001
    const val EXTRA_NAME="EXTRA NAME"
    const val SERVICIU_ALES="ServiciuAles"
    const val ZI_ALEASA="ZZ/LL/AA"
    const val nume_petowner_activitate_zi_aleasa="CevaZiAleasa"
    const val nume_activitate_zi_aleasa_plus_data="Ceva DD/MM/YY"
    const val activitate_zi_aleasa_ora = "12:00"
    const val pet_ales="Test"
    const val pet_ales_pet_owner="Bubica"
    const val poza_aleasa="Placeholder"
    const val email_selected_marker="Cevamarker"
    const val serviciu_ales_nume = "serviciualesdepetownernume"
    const val serviciu_ales_pret = "serviciualesdepetownerpret"
    const val serviciu_ales_descriere = "serviciualesdepetownerdescriere"
    const val serviciu_ales_proprietar = "ownerOfSelectedService"
    const val REQUEST_SELECTED_BY_PETOWNER_DATE="RequestSelectedBYPetownerDATE"
    const val REQUEST_SELECTED_BY_PETOWNER_HOUR="RequestSelectedBYPetownerHOUR"
    const val REQUEST_SELECTED_BY_PETOWNER_SERVICE_NAME="RequestSelectedBYPetownerSERVICENAME"
    const val REQUEST_SELECTED_BY_PETOWNER_PET_NAME="RequestSelectedBYPetownerPetName"
    const val REQUEST_SELECTED_BY_PETOWNER_PETOWNERID="RequestSelectedBYPetownerPETOWNERID"
    const val Selected_request_ID ="Ytlni"
    const val petSitterRequestPet="JUPON"
    const val petSitterRequestService="Hujaoy"
    const val petSitterRequestSender="Kloaiy"
    const val petSitterRequestID="Dubrv"
    const val chat_with_other_user_ID="Juhy"
}